# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_Password Example.ipynb.

# %% auto 0
__all__ = ['hashed_password']

# %% ../01_Password Example.ipynb 1
import getpass
import bcrypt

hashed_password = bcrypt.hashpw(getpass.getpass("password: ").encode("utf-8"), bcrypt.gensalt()).decode()
print(hashed_password)
